---
# tasks file for myapache
- name: "installing httpd "
  package:
    name: "httpd"
    state: present
- name: "installing php"
  package:
    name: "php"
    state: "present"
- name: "copying the data"
  copy:
    dest: "/var/www/html/index.php"
    src: "index.php"
- name: "starting the httpd"
  service:
    name: "httpd"
    state: started
